services:
  api:
    build:
      context: ./src
      dockerfile: TextProcessor.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app-network

  web:
    build:
      context: ./src/TextProcessor.Web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    build:
      context: ./src/TextProcessor.Web/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
